# Generated by Django 5.2.7 on 2026-03-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt_password',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
